install.packages("readxl")
library(readxl)
setwd("L:/BUT/SD/Promo 2023/lmarnas/R/TD3")
pokemon <- read_excel(path = "pokemon.xlsx",sheet = "pokemon")
dim(pokemon)
summary(pokemon)
pokemon$is_legendary <- as.factor(pokemon$is_legendary)
pokemon$generation <- as.factor(pokemon$generation)
pokemon$type <- as.factor(pokemon$type)
summary(pokemon)
med = median(pokemon$attack)
pokemon$attack_group = ifelse(test = pokemon$attack >= med, yes = "attack+", no = "attack-")
pokemon$attack_group = as.factor(pokemon$attack_group)
summary(pokemon)
pokemon$water_fire = ifelse(pokemon$type %in% c("water", "fire"),"yes", "no")
pokemon$water_fire = as.factor(pokemon$water_fire)
summary(pokemon$water_fire)
Q3_att = quantile(pokemon$attack, probs = 0.75)
Q3_def = quantile(pokemon$defense, probs = 0.75)
Q3_spe = quantile(pokemon$speed, probs = 0.75)
pokemon$best = ifelse(pokemon$attack > Q3_att &
                        pokemon$defense > Q3_def &
                        pokemon$speed > Q3_spe, "yes", "no")
pokemon$best = as.factor(pokemon$best)
summary(pokemon)
requete = subset(pokemon, is.na(weight_kg))
View(requete)
requete = subset(pokemon, !is.na(weight_kg))
View(requete)
med_weight_kgna = median(pokemon$weight_kg, na.rm = TRUE)
pokemon$weight_kg = ifelse(is.na(pokemon$weight_kg), med_weight_kgna, pokemon$weight_kg)
med_height_mna = median(pokemon$height_m, na.rm = TRUE)
pokemon$height_m = ifelse(is.na(pokemon$height_m), med_height_mna, pokemon$height_m)